branches:
  - "+([1-9])?(.{+([1-9]),x}).x"
  - master
  - next
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  -
    - semantic-release-slack-bot
    - notifyOnSuccess: true
      notifyOnFail: true
      markdownReleaseNotes: true
      onSuccessTemplate:
        text: "$package_name version v$npm_package_version!\n\n\n$release_notes"
  -
    - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/npm"
  -
    - "@semantic-release/github"
    - assets:
      - path: "dist/**/*.js"
        label: Packaged JS Code
      labels: [failure]
      releasedLabels: ['releases/<%= nextRelease.gitTag %>']
      assignees: trilom
  -
    - "@semantic-release/git"
    - assets: [CHANGELOG.md, package.json, yarn.lock, 'dist/**/*.js']
      message: >
        chore(release): 🎉🦍🎉 Release <%= nextRelease.version %> -
        <%= new Date().toLocaleDateString('en-US', {year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }) %> [skip ci]
        <%= nextRelease.notes %>