name: Contribution Workflow
env:
  isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
on: [pull_request]
jobs:
  # make sure we can build
  build:
    name: yarn install && tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
  # unit test with jest
  test-unit:
    name: jest unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
      - run: yarn test-coverage
  # integration test with jest
  test-integration:
    name: jest integration tests
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
      - run: yarn test-integration
  # lint code in github check
  lintdog-fork:
    name: eslintdog (reviewdog)
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
      - name: Lint and report
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: '--ext .ts ./'
  # lint code and comment back if possible
  lintdog:
    name: eslintdog (reviewdog)
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
      - name: Lint and report
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.TRILOM_BOT_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts ./'
  # format and push code back if not forked branch
  format_check_push:
    name: prettier
    runs-on: ubuntu-latest
    needs: [lintdog, lintdog-fork]
    if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}  
    steps:
      - uses: actions/checkout@v2 # checkout for forks
        if: contains(env.isFork, 'true')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - uses: actions/checkout@v2 # checkout for PR
        if: contains(env.isFork, 'false')
        with:
          token: ${{ secrets.TRILOM_BOT_TOKEN }}  
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: yarn build
      - run: yarn format-check
      - name: yarn format and push code if check failed
        if: failure() && github.actor != 'trilom-bot' && contains(env.isFork, 'false')
        env:
          GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}  
        run: |
          yarn format
          sudo yarn clean
          git config --local user.email "trilom-bot@trailmix.me"
          git config --local user.name "trilom-bot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Adding format changes 🤖" -a
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:refs/heads/${{ github.head_ref }} && exit 0